[project]
name = "syft-process-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "eelcovdw", email = "eelcovdw@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "anywidget>=0.9",
    "cloudpickle>=3.1.1",
    "jinja2>=3.1.6",
    "psutil>=5.9.5", # Match Colab psutil version
    "pydantic>=2.11", # Match Colab pydantic
    "setproctitle>=1.3.7",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "anywidget[dev]>=0.9",
    "jupyter>=1.1.1",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-xdist>=3.8.0",
]
