[project]
name = "syft-process-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "eelcovdw", email = "eelcovdw@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "cloudpickle>=3.1.1",
    "fastapi>=0.118.0",
    "importlib>=1.0.4",
    "jinja2>=3.1.6",
    "jupyter-dark-detect>=0.1.0",
    "psutil>=7.1.1",
    "pydantic>=2.12.3",
    "setproctitle>=1.3.7",
    "uvicorn>=0.37.0",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
jupyter = ["jupyter>=1.1.1"]
