# Pre-commit hooks for syft-client
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Code formatting (auto-fix)
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10

  # Import sorting (auto-fix)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Linting (warnings)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503,W504', '--max-complexity=10']

  # Security scanning (CRITICAL for AI code)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml', '-r', 'syft_client']

  # General code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Security
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=1000']

      # File formatting
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml

      # Merge conflicts
      - id: check-merge-conflict

      # Python specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  # Type checking (advisory - won't block commits)
  # Run manually with: SKIP= pre-commit run mypy --all-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --check-untyped-defs
        ]
        additional_dependencies: ['types-requests']
        pass_filenames: true
        # Skip by default in pre-commit (advisory mode)
        stages: [manual]
