[project]
name = "syft-job"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rasswanth-s", email = "43314053+rasswanth-s@users.noreply.github.com" }
]
requires-python = ">=3.9"
dependencies = ["syft-client"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
syft-client = { workspace = true }
